  CREATE SCHEMA IF NOT EXISTS silver;
  DROP TABLE IF EXISTS silver.sinistros CASCADE;
  CREATE TABLE silver.sinistros (
      ano_arquivo INT NOT NULL,
      sinistro_id BIGINT NOT NULL,
      pessoa_id   BIGINT NOT NULL,
      veiculo_id  BIGINT,
      data_hora TIMESTAMP,
      dia_semana_num INT,
      uf VARCHAR(2),
      municipio VARCHAR,
      delegacia VARCHAR,
      latitude  DOUBLE PRECISION,
      longitude DOUBLE PRECISION,
      causa_acidente VARCHAR,
      tipo_acidente VARCHAR,
      fase_dia VARCHAR,
      sentido_via VARCHAR,
      condicao_meteorologica VARCHAR, 
      tipo_pista VARCHAR,
      tracado_via VARCHAR,
      caracteristicas_via VARCHAR,
      tipo_envolvido VARCHAR,
      estado_fisico VARCHAR,
      faixa_etaria VARCHAR,
      sexo VARCHAR,
      tipo_veiculo VARCHAR,
      faixa_idade_veiculo VARCHAR,
      PRIMARY KEY (sinistro_id, pessoa_id)
  );
